name: dex security review

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Get PR diff
        run: |
          git fetch origin "${{ github.event.pull_request.base.sha }}"
          git fetch origin "${{ github.event.pull_request.head.sha }}"

          git diff "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}" -- > pr.diff

          echo "===== PR DIFF ====="
          cat pr.diff

      - name: Show PR information
        run: | 
          echo "Repository: ${{ github.repository }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
